import { useState } from "react";
import { useNavigate } from "react-router-dom";

const SECTIONS = [
  {
    id: "how-it-works",
    icon: "🔄",
    title: "How AlEcom Works",
    content: [
      {
        type: "steps",
        items: [
          { n: "1", t: "Seller lists a product or service", d: "Sellers create listings which are reviewed and approved by AlEcom admin before going live." },
          { n: "2", t: "Buyer pays via MoMo or Wallet",    d: "The buyer sends MoMo to the AlEcom admin number (0549548274) using a unique reference code, or pays from their AlEcom wallet balance." },
          { n: "3", t: "Admin verifies the payment",       d: "AlEcom admin checks their MoMo records, confirms the reference code matches, and activates the order. This normally happens within 2 hours during business hours." },
          { n: "4", t: "Seller accepts and delivers",      d: "Once payment is verified, the seller is notified. They accept the order, prepare the item or service, and mark it as delivered on the platform." },
          { n: "5", t: "Buyer confirms receipt",           d: "The buyer inspects the item and clicks 'Confirm Delivery'. This releases the escrow funds to the seller's AlEcom wallet." },
          { n: "6", t: "Seller withdraws earnings",        d: "The seller requests a withdrawal from their AlEcom wallet. Admin manually sends the MoMo payment to the seller's registered number within 24 hours." },
        ],
      },
    ],
  },
  {
    id: "escrow",
    icon: "🔒",
    title: "Escrow & Payment Protection",
    content: [
      {
        type: "text",
        text: "All payments on AlEcom are held in escrow — a secure holding state managed by AlEcom. Money is never transferred directly between buyer and seller. It always flows through AlEcom escrow first.",
      },
      {
        type: "points",
        label: "What escrow protects against:",
        items: [
          "Sellers who take payment and disappear without delivering",
          "Buyers who claim they did not receive an item when they did",
          "Disputes over item quality or service delivery",
          "Fraudulent transactions and impersonation",
        ],
      },
      {
        type: "text",
        text: "AlEcom charges a small escrow fee (2% of transaction value) and a platform commission (10% of seller earnings) to maintain the escrow service, dispute resolution, and platform operations.",
      },
    ],
  },
  {
    id: "cancellations",
    icon: "↩️",
    title: "Cancellations & Refunds",
    content: [
      {
        type: "table",
        rows: [
          { scenario: "Order cancelled before seller accepts",         outcome: "Full refund to buyer wallet within minutes" },
          { scenario: "Order cancelled after seller accepts",          outcome: "Admin reviews. Refund issued if seller agrees or has not delivered" },
          { scenario: "Seller cannot fulfil (e.g. out of stock)",      outcome: "Full refund to buyer wallet. Seller account flagged" },
          { scenario: "Buyer did not receive item",                    outcome: "Buyer raises dispute. Admin reviews evidence. Refund if seller cannot prove delivery" },
          { scenario: "Item received but damaged or wrong",            outcome: "Buyer raises dispute within 7 days. Admin decides based on photos/evidence" },
          { scenario: "MoMo wallet refunds",                          outcome: "Wallet refunds are instant. MoMo cash refunds take up to 24 hours as admin must send manually" },
          { scenario: "Escrow fee and commission",                     outcome: "Not refunded if order was delivered and confirmed by buyer" },
        ],
      },
    ],
  },
  {
    id: "momo-payments",
    icon: "📱",
    title: "MoMo Payments — Important Rules",
    content: [
      {
        type: "alert",
        variant: "warning",
        text: "AlEcom admin number: 0549548274. AlEcom will never ask you to send money to any other number. Do not make payments to any number claimed by 'AlEcom' that is not this official number.",
      },
      {
        type: "points",
        label: "Rules you must follow when paying via MoMo:",
        items: [
          "Always use the unique reference code generated by the platform (e.g. AlEcom-K7MX2P) as your narration when sending",
          "Submit your transaction ID (from your MoMo confirmation SMS) on the platform within 30 minutes",
          "Send the exact amount shown on the platform — no partial payments",
          "Use only your registered phone number to send",
        ],
      },
      {
        type: "points",
        label: "What happens if things go wrong:",
        items: [
          "Wrong number sent to: AlEcom is not liable. Contact your MoMo provider (MTN: 100, Vodafone: 110). AlEcom cannot reverse MoMo transactions.",
          "SIM card stolen and used to send payment: Report to your network provider immediately. AlEcom will freeze the order pending your network provider's investigation.",
          "Sent correct amount but wrong reference: Contact admin at alecommerce123@gmail.com with your MoMo transaction ID. Admin will match and verify manually.",
          "Admin phone off / delayed verification: Orders pending over 2 hours are automatically escalated. Contact support. Your money is safe as no funds move until admin verifies.",
        ],
      },
    ],
  },
  {
    id: "seller-payments",
    icon: "💰",
    title: "How Sellers Receive Their Money",
    content: [
      {
        type: "text",
        text: "Sellers do not receive money directly to their MoMo when a sale completes. Instead, the amount is credited to their AlEcom wallet. To receive the money on your phone, you must request a withdrawal.",
      },
      {
        type: "steps",
        items: [
          { n: "1", t: "Buyer confirms delivery",       d: "This triggers automatic release of escrow funds to your AlEcom wallet (minus platform commission)." },
          { n: "2", t: "Check your wallet",             d: "Go to Wallet — your earnings appear there immediately after the buyer confirms." },
          { n: "3", t: "Request a withdrawal",          d: "Click 'Withdraw Funds', enter your registered MoMo number and the amount you want." },
          { n: "4", t: "Admin sends the MoMo payment",  d: "Admin processes your withdrawal within 24 hours during business days and sends MoMo directly to your number." },
          { n: "5", t: "Confirm receipt",               d: "You receive an SMS from MoMo and an email from AlEcom confirming the payment." },
        ],
      },
      {
        type: "alert",
        variant: "info",
        text: "If your wallet shows a balance but you haven't received a withdrawal: First check that you submitted a withdrawal request. Then check that your MoMo number on file is correct. Contact admin at alecommerce123@gmail.com if the issue persists after 24 hours.",
      },
    ],
  },
  {
    id: "disputes",
    icon: "⚖️",
    title: "Disputes & Fraud Claims",
    content: [
      {
        type: "text",
        text: "AlEcom has a structured dispute process. Do not attempt to resolve disputes outside the platform — always use the official dispute channel to ensure your protection.",
      },
      {
        type: "steps",
        items: [
          { n: "1", t: "Raise a dispute on the platform", d: "Go to your order → click 'Raise Dispute'. Describe the problem clearly. Escrow is frozen — no money moves until resolved." },
          { n: "2", t: "Admin reviews within 48 hours",   d: "Both parties will be contacted. You may be asked to provide photos, screenshots, or other evidence." },
          { n: "3", t: "Admin decision",                  d: "Admin makes a final decision based on evidence. This may result in a full refund, partial refund, or release of funds to seller." },
          { n: "4", t: "Appeal",                          d: "If you believe the decision is wrong, email alecommerce123@gmail.com with 'DISPUTE APPEAL' in the subject line within 7 days." },
        ],
      },
      {
        type: "alert",
        variant: "danger",
        text: "AlEcom is a marketplace platform connecting buyers and sellers. AlEcom is not a party to the sale contract between buyer and seller. In cases of legal dispute, AlEcom can provide transaction records as evidence but is not responsible for the underlying sale agreement.",
      },
    ],
  },
  {
    id: "stock",
    icon: "📦",
    title: "Out of Stock & Unavailable Products",
    content: [
      {
        type: "points",
        label: "What happens when a product runs out:",
        items: [
          "Products with stock tracking: automatically show 'Out of Stock' when quantity reaches zero. Buyers cannot place orders.",
          "Products without stock tracking: if a seller cannot fulfil an order they accepted, they must cancel. The buyer receives a full automatic refund to their wallet.",
          "Sellers who repeatedly cancel due to unavailable stock may have their listings suspended by admin.",
          "Buyers should always message the seller to confirm availability before paying for high-value items.",
        ],
      },
    ],
  },
  {
    id: "admin-backup",
    icon: "🛡️",
    title: "What Happens If Admin is Unavailable",
    content: [
      {
        type: "text",
        text: "AlEcom provides a payment verification SLA (Service Level Agreement). All pending payments are automatically escalated if not verified within the target window.",
      },
      {
        type: "table",
        rows: [
          { scenario: "Payment pending — 30 minutes",   outcome: "Automatic reminder email sent to admin" },
          { scenario: "Payment pending — 2 hours",      outcome: "Escalation email sent to backup contact. Order timer extended" },
          { scenario: "Payment pending — 4 hours",      outcome: "Buyer notified of delay. Order remains active — money is safe" },
          { scenario: "Admin unreachable for 24 hours", outcome: "Email alecommerce123@gmail.com marked urgent. AlEcom operations paused for new payments" },
        ],
      },
      {
        type: "alert",
        variant: "info",
        text: "Your money is always safe. No funds leave escrow until admin verifies. If admin is unavailable, your money remains locked and protected — it cannot be touched by anyone until verification is complete.",
      },
    ],
  },
  {
    id: "liability",
    icon: "📋",
    title: "Platform Liability & Legal",
    content: [
      {
        type: "points",
        label: "AlEcom's responsibilities:",
        items: [
          "Providing a secure platform for buyers and sellers to transact",
          "Holding funds in escrow until both parties are satisfied",
          "Verifying MoMo payments and crediting wallets accurately",
          "Resolving disputes fairly based on available evidence",
          "Maintaining transaction records for up to 2 years",
        ],
      },
      {
        type: "points",
        label: "AlEcom is not responsible for:",
        items: [
          "The quality, legality, or accuracy of items listed by sellers",
          "Losses arising from buyer or seller misrepresentation",
          "MoMo transactions made to wrong numbers by user error",
          "Delays caused by MoMo network issues outside AlEcom's control",
          "Any loss exceeding the transaction value in dispute",
        ],
      },
      {
        type: "text",
        text: "In all cases, AlEcom's maximum liability to any user is limited to the value of the transaction in question. AlEcom complies with Ghanaian commercial law and will cooperate fully with legitimate legal proceedings by providing transaction records.",
      },
    ],
  },
  {
    id: "contact",
    icon: "📞",
    title: "Contact & Support",
    content: [
      {
        type: "contact",
        items: [
          { icon: "✉️", label: "Email Support",        value: "alecommerce123@gmail.com",  sub: "Respond within 24 hours" },
          { icon: "📱", label: "Admin MoMo Number",    value: "0549548274",               sub: "For payments only — not calls" },
          { icon: "🕐", label: "Support Hours",        value: "Monday – Saturday",         sub: "8:00 AM – 8:00 PM GMT" },
          { icon: "⚡", label: "Urgent Disputes",      value: "alecommerce123@gmail.com",  sub: "Subject: URGENT DISPUTE #OrderID" },
        ],
      },
    ],
  },
];

export default function Policy() {
  const navigate = useNavigate();
  const [active, setActive] = useState("how-it-works");

  const current = SECTIONS.find(s => s.id === active);

  return (
    <div className="page-wrapper">
      <div className="container" style={{ paddingTop: 28, maxWidth: 960 }}>

        {/* Header */}
        <div style={{ marginBottom: 32, textAlign: "center" }}>
          <div style={{
            display: "inline-flex", alignItems: "center", gap: 10,
            background: "var(--accent-glow)", border: "1px solid rgba(26,86,219,0.2)",
            borderRadius: 20, padding: "5px 16px", marginBottom: 16,
          }}>
            <span style={{ fontSize: 12, color: "var(--accent)", fontWeight: 700, letterSpacing: "0.5px" }}>
              OFFICIAL PLATFORM POLICY
            </span>
          </div>
          <h1 style={{ fontFamily: "var(--font-display)", fontSize: 32, fontWeight: 700, marginBottom: 10 }}>
            How AlEcom Works
          </h1>
          <p style={{ fontSize: 16, color: "var(--text-muted)", maxWidth: 560, margin: "0 auto", lineHeight: 1.7 }}>
            Everything you need to know about payments, escrow, disputes, refunds, and your rights as a buyer or seller.
          </p>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "220px 1fr", gap: 28, alignItems: "start" }}>

          {/* Sidebar nav */}
          <div style={{
            position: "sticky", top: 88,
            background: "var(--surface)", border: "1px solid var(--border)",
            borderRadius: "var(--radius-xl)", overflow: "hidden",
          }}>
            {SECTIONS.map(s => (
              <button
                key={s.id}
                onClick={() => setActive(s.id)}
                style={{
                  width: "100%", padding: "12px 16px",
                  display: "flex", alignItems: "center", gap: 10,
                  border: "none", borderBottom: "1px solid var(--border)",
                  background: active === s.id ? "var(--accent-glow)" : "transparent",
                  borderLeft: `3px solid ${active === s.id ? "var(--accent)" : "transparent"}`,
                  cursor: "pointer", textAlign: "left",
                  transition: "all 0.15s", fontFamily: "var(--font-body)",
                }}
              >
                <span style={{ fontSize: 16 }}>{s.icon}</span>
                <span style={{
                  fontSize: 13, fontWeight: active === s.id ? 700 : 500,
                  color: active === s.id ? "var(--accent)" : "var(--text-secondary)",
                  lineHeight: 1.3,
                }}>
                  {s.title}
                </span>
              </button>
            ))}
          </div>

          {/* Content panel */}
          <div>
            <div style={{
              background: "var(--surface)", border: "1px solid var(--border)",
              borderRadius: "var(--radius-xl)", padding: "28px 32px",
            }}>
              <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 24 }}>
                <div style={{
                  width: 48, height: 48, borderRadius: "var(--radius)",
                  background: "var(--accent-glow)", display: "flex",
                  alignItems: "center", justifyContent: "center", fontSize: 24,
                }}>
                  {current.icon}
                </div>
                <h2 style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 22 }}>
                  {current.title}
                </h2>
              </div>

              {current.content.map((block, bi) => (
                <div key={bi} style={{ marginBottom: 24 }}>

                  {block.type === "text" && (
                    <p style={{ fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.8 }}>
                      {block.text}
                    </p>
                  )}

                  {block.type === "alert" && (
                    <div style={{
                      padding: "14px 16px",
                      background: block.variant === "warning" ? "rgba(217,119,6,0.08)"
                               : block.variant === "danger"  ? "rgba(220,38,38,0.08)"
                               : "rgba(26,86,219,0.07)",
                      border: `1px solid ${
                        block.variant === "warning" ? "rgba(217,119,6,0.25)"
                      : block.variant === "danger"  ? "rgba(220,38,38,0.25)"
                      : "rgba(26,86,219,0.2)"}`,
                      borderRadius: "var(--radius-sm)",
                      fontSize: 14, lineHeight: 1.7,
                      color: block.variant === "warning" ? "#92400e"
                           : block.variant === "danger"  ? "#991b1b"
                           : "#1e3a8a",
                    }}>
                      {block.text}
                    </div>
                  )}

                  {block.type === "steps" && (
                    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
                      {block.items.map((step, i) => (
                        <div key={i} style={{ display: "flex", gap: 14 }}>
                          <div style={{
                            width: 30, height: 30, borderRadius: "50%", flexShrink: 0,
                            background: "var(--accent)", color: "#fff",
                            display: "flex", alignItems: "center", justifyContent: "center",
                            fontWeight: 800, fontSize: 13,
                          }}>{step.n}</div>
                          <div style={{ paddingTop: 4 }}>
                            <div style={{ fontWeight: 700, fontSize: 15, marginBottom: 4 }}>{step.t}</div>
                            <div style={{ fontSize: 14, color: "var(--text-muted)", lineHeight: 1.6 }}>{step.d}</div>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}

                  {block.type === "points" && (
                    <div>
                      {block.label && (
                        <div style={{ fontWeight: 700, fontSize: 15, marginBottom: 12 }}>{block.label}</div>
                      )}
                      <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
                        {block.items.map((pt, i) => (
                          <div key={i} style={{ display: "flex", gap: 10, alignItems: "flex-start" }}>
                            <div style={{
                              width: 6, height: 6, borderRadius: "50%",
                              background: "var(--accent)", marginTop: 7, flexShrink: 0,
                            }} />
                            <div style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.65 }}>{pt}</div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {block.type === "table" && (
                    <div style={{ overflowX: "auto" }}>
                      <table style={{ width: "100%", borderCollapse: "collapse" }}>
                        <thead>
                          <tr>
                            <th style={{ textAlign: "left", padding: "10px 14px", background: "var(--surface-2)", fontSize: 13, fontWeight: 700, borderBottom: "2px solid var(--border)", color: "var(--text-muted)" }}>
                              Situation
                            </th>
                            <th style={{ textAlign: "left", padding: "10px 14px", background: "var(--surface-2)", fontSize: 13, fontWeight: 700, borderBottom: "2px solid var(--border)", color: "var(--text-muted)" }}>
                              What Happens
                            </th>
                          </tr>
                        </thead>
                        <tbody>
                          {block.rows.map((row, i) => (
                            <tr key={i}>
                              <td style={{ padding: "12px 14px", borderBottom: "1px solid var(--border)", fontSize: 14, fontWeight: 600, verticalAlign: "top" }}>
                                {row.scenario}
                              </td>
                              <td style={{ padding: "12px 14px", borderBottom: "1px solid var(--border)", fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.6 }}>
                                {row.outcome}
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  )}

                  {block.type === "contact" && (
                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 }}>
                      {block.items.map((c, i) => (
                        <div key={i} style={{
                          padding: "16px 18px", background: "var(--surface-2)",
                          border: "1px solid var(--border)", borderRadius: "var(--radius-lg)",
                        }}>
                          <div style={{ fontSize: 24, marginBottom: 8 }}>{c.icon}</div>
                          <div style={{ fontSize: 12, color: "var(--text-muted)", marginBottom: 4, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.5px" }}>
                            {c.label}
                          </div>
                          <div style={{ fontWeight: 700, fontSize: 15, marginBottom: 2 }}>{c.value}</div>
                          <div style={{ fontSize: 12, color: "var(--text-muted)" }}>{c.sub}</div>
                        </div>
                      ))}
                    </div>
                  )}

                </div>
              ))}
            </div>

            {/* Navigation between sections */}
            <div style={{ display: "flex", justifyContent: "space-between", marginTop: 20 }}>
              {SECTIONS.findIndex(s => s.id === active) > 0 ? (
                <button
                  onClick={() => setActive(SECTIONS[SECTIONS.findIndex(s => s.id === active) - 1].id)}
                  style={{
                    background: "var(--surface)", border: "1.5px solid var(--border)",
                    borderRadius: "var(--radius-sm)", padding: "10px 18px",
                    cursor: "pointer", fontSize: 14, fontWeight: 600,
                    color: "var(--text-secondary)", fontFamily: "var(--font-body)",
                  }}
                >
                  ← Previous
                </button>
              ) : <div />}
              {SECTIONS.findIndex(s => s.id === active) < SECTIONS.length - 1 ? (
                <button
                  onClick={() => setActive(SECTIONS[SECTIONS.findIndex(s => s.id === active) + 1].id)}
                  style={{
                    background: "var(--accent)", border: "none",
                    borderRadius: "var(--radius-sm)", padding: "10px 18px",
                    cursor: "pointer", fontSize: 14, fontWeight: 600,
                    color: "#fff", fontFamily: "var(--font-body)",
                  }}
                >
                  Next →
                </button>
              ) : (
                <button
                  onClick={() => navigate("/")}
                  style={{
                    background: "var(--success)", border: "none",
                    borderRadius: "var(--radius-sm)", padding: "10px 18px",
                    cursor: "pointer", fontSize: 14, fontWeight: 600,
                    color: "#fff", fontFamily: "var(--font-body)",
                  }}
                >
                  Done — Go to Marketplace
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
